### ISSUE TITLE
bot failed to notice new version (10.1) of GDB

### ISSUE THREAD

**Issue by phil-blain** [regro/cf-scripts#1246]
From the meta.yml:

```yaml
$ head meta.yaml 

{% set name = "gdb" %}
{% set version = "9.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/gdb/gdb-{{ version }}.tar.xz
```

GDB 10.1 was released on October 24th but no PR has been opened in https://github.com/conda-forge/gdb-feedstock/

Is it a bug or a special logic needs to be added for each tarball sources?
