### ISSUE TITLE
Bug rerendering multi-output feedstock

### ISSUE THREAD

**Issue by tdegeus** [regro/cf-scripts#1423]
I have a multi-output feedstock. For ARM OSX migration I'm seeking to build on of the outputs only for Python >= 3.9 (the reason is not relevant for this issue), the other output does not use Python at all.

Now when I do:

```yaml
build:
  number: 0
  skip: true  # [py<39 and osx and not x86_64]
```

without any Python dependency for the Python independent part of this feedstock, the bot fails to create the OSX ARM builds all-together. It only works when I put some unused Python dependency everywhere.

See https://github.com/conda-forge/gmatelastoplasticqpot-feedstock/pull/23
