### ISSUE TITLE
Pinning not ignored

### ISSUE THREAD

**Issue by tdegeus** [regro/cf-scripts#1429]
When I do 
```yaml
build:
   ignore_run_exports:
     - hdf5

 requirements:
   host:
     - hdf5 *
   run:
     - hdf5 *
```
the bot fails to ignore the pinning of HDF5 (ref: https://github.com/conda-forge/highfive-feedstock/pull/24).

Instead the bot correctly ignores pinning of HDF5 when I do:
```yaml
build:
   ignore_run_exports_from:
     - hdf5 *

 requirements:
   host:
     - hdf5 *
   run:
     - hdf5 *
```
(ref: https://github.com/conda-forge/highfive-feedstock/pull/25)

> A personal note: in both cases I find the required syntax quite verbose. I would like to use only `hdf5 *` in requirements or `hdf5` in `ignore_run_expots`.

**Comment by tdegeus** [comment]
@xhochy Comment that just
```yaml
 requirements:
   host:
     - hdf5 *
   run:
     - hdf5 *
```
(without `ignore_run_exports` or `ignore_run_exports_from`) works. Which indeed seems to be the case: https://github.com/conda-forge/highfive-feedstock/pull/26
