### ISSUE TITLE
Bot not updating sha for different platforms

### ISSUE THREAD

**Issue by minrk** [regro/cf-scripts#1515]
I see several closed issues about bots not updating shas, but nodejs is getting incorrect shas in PRs like https://github.com/conda-forge/nodejs-feedstock/pull/249

We have different sources for Windows and non-Windows, which look like:

```yaml
source:
  # checksums from https://nodejs.org/dist/vX.Y.Z/SHASUMS256.txt.asc
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}.tar.gz  # [not win]
  sha256: 3cf4ef8ede328389a6b0150eb94480fce9bdd00e23051d7bcada5af7473b28b1  # [not win]
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}-win-x64.zip  # [win]
  sha256: fcb3a52c14e70ffdc5364952e1a6c40d4d02431667183604d62031790a9803d8  # [win]
```

The bot is issuing PRs with only the `not win` sha _field_ updated, to the _value_ for the `win` url. It seems like this is exactly what was fixed by #163, but the PRs we are getting are not quite right.

Happy to tweak our yaml if it's just not specified how it would expect.
