### ISSUE TITLE
node creation errors / warnings

### ISSUE THREAD

**Issue by beckermr** [regro/cf-scripts#1578]
- `Error adding datafusion to the graph: KeyError('linux64')`
 - UserWarnings from missing environment variables
 - pkg_resources warnings from parsing versions with build strings
 - `Error adding futures to the graph: TypeError("'<' not supported between instances of 'list' and 'tuple'")`
 - `Error adding gfortran_impl_osx-64 to the graph: TypeError("'NoneType' object is not callable")`

**Comment by beckermr** [comment]
```
Problematic recipe:
THIS IS NOT THE BRANCH THAT YOU WANT. master GOT DEPRECATED IN FAVOR OF main
package:
  name: ndcctools
  version: 7.4.3
source:
  url: http://ccl.cse.nd.edu/software/files/cctools-7.4.3-source.tar.gz
  sha256: 6b9738a8850b1f6d41b5c29068110cabd54ba035dc3cddab82992cda01d6a6fd
build:
  number: 0
  rpaths:
    - lib/
requirements:
  build:
    - gcc_linux-64 9.*
    - gxx_linux-64 9.*
    - m4
    - swig
    - make
  host:
    - python
    - zlib
    - libnsl
    - libopenssl-static
    - openssl
  run:
    - python
    - zlib
    - libnsl
    - openssl
    - conda-pack
test:
  imports:
    - work_queue
  commands:
    - makeflow -h
    - work_queue_worker -h
    - work_queue_factory -h
about:
  home: http://ccl.cse.nd.edu/
  license: GPL-2.0-only
  license_file: COPYING
  summary: The Cooperative Computing Tools contains Chirp, Makeflow, JX, and Work Queue.
  description: |
    The Cooperative Computing Tools (cctools) are a collection of programs that
    enable large scale distributed computing on systems such as clusters,
    clouds, and grids. These tools are commonly used in fields of science and
    engineering that rely on large amounts of computing.
  doc_url: https://cctools.readthedocs.io/
  dev_url: https://github.com/cooperative-computing-lab/cctools
extra:
  recipe-maintainers:
    - btovar
    - dthain
```
