### ISSUE TITLE
Bot modifying `conda_build_config.yaml` when applying migration

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#1981]
Recently found a CUDA 12 bot migration PR ( https://github.com/conda-forge/onnxruntime-feedstock/pull/92 ) where the bot added the following content to `conda_build_config.yaml`:

```yaml
cudnn:                                            # [linux64]
  - undefined                                     # [linux64]
cuda_compiler_version:                            # [linux64]
  - None                                          # [linux64]
docker_image:                                     # [linux64]
  - quay.io/condaforge/linux-anvil-cos7-x86_64    # [linux64]
cdt_name:                                         # [linux64]
  - cos7                                          # [linux64]
```

Searching the history here, am finding issue ( https://github.com/regro/cf-scripts/issues/1356 ) and PR ( https://github.com/regro/cf-scripts/pull/1359 )

It does look like the `conda_build_config.yaml` gets modified by that bot code. Though not recalling the history as to why it is needed (and whether it is still needed)

Raising to discuss further and possibly revise the code in the bot depending on the discussion
