### ISSUE TITLE
Migrate pinned packages to use `pin_run_as_build`

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#227]
From @isuruf (would you be able to flesh this out a little)

**Comment by isuruf** [comment]
In conda-forge-pinning, we have things like,

```yaml
pin_run_as_build:
   readline:
     max_pin: x
   snappy:
      max_pin: x.x.x
```

`run_exports` should be added to readline package,

```yaml
build:
  run_exports:
    - {{ pin_subpackage("readline", max_pin="x") }}
```
and for snappy,
```yaml
build:
  run_exports:
    - {{ pin_subpackage("snappy", max_pin="x.x.x") }}
```
