### ISSUE TITLE
New migrator: combine adjacent conditions in v1 recipes

### ISSUE THREAD

**Issue by mgorny** [regro/cf-scripts#3833]
As noted in #3832, I think it would make sense to have a migrator to combine adjacent conditions in v1 recipes into one.

For example, the following:

```yaml
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: cython
```

could be combined into:

```yaml
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython
```

This would both be useful as post-migrator for other migrators (e.g. `CrossPythonMigrator`) that can produce such output, and to clean up recipes created via `conda-recipe-manager`.

If this sounds fine, I can try implementing my first minimigrator :-).

CC @wolfv
