### ISSUE TITLE
v1 condition combining can alter command order

### ISSUE THREAD

**Issue by mgorny** [regro/cf-scripts#3933]
Just found a potential issue with the minimigrator combining conditions in v1 recipes.

For example, PyTorch is about to have a test phase that's roughly:

```yaml
        script:
#...
          - if: unix
            then: test -f $PREFIX/lib/libtorch_python${SHLIB_EXT}
          - if: win
            then: if not exist %LIBRARY_BIN%\torch_python.dll exit 1
          - if: win
            then: if not exist %SP_DIR%\torch\lib\torch_python.lib exit 1
          - if: win
            then: if not exist %SP_DIR%\torch\lib\_C.lib exit 1
          - if: unix
            then: export OMP_NUM_THREADS=4
# ...
          - cd cmake_test
          - if: unix
            then: cmake -GNinja -DCMAKE_CXX_STANDARD=17 -DWITH_TORCH_PYTHON=ON $CMAKE_ARGS .
          - if: win
            then: cmake -GNinja -DCMAKE_CXX_STANDARD=17 -DWITH_TORCH_PYTHON=ON %CMAKE_ARGS% .
          - if: unix
            then: cmake --build .
          - if: win
            then: cmake --build . --config Release
```

This gets combined into:

```yaml
        script:
#...
          - if: unix
            then:
              - test -f $PREFIX/lib/libtorch_python${SHLIB_EXT}
              - cmake -GNinja -DCMAKE_CXX_STANDARD=17 -DWITH_TORCH_PYTHON=ON $CMAKE_ARGS .
              - cmake --build .
          - if: win
            then:
              - if not exist %LIBRARY_BIN%\torch_python.dll exit 1
              - if not exist %SP_DIR%\torch\lib\torch_python.lib exit 1
              - if not exist %SP_DIR%\torch\lib\_C.lib exit 1
              - cmake -GNinja -DCMAKE_CXX_STANDARD=17 -DWITH_TORCH_PYTHON=ON %CMAKE_ARGS% .
              - cmake --build . --config Release
# ...
          - cd cmake_test
```

Note that commands that were supposed to follow `cd cmake_test` ended up being folded into conditions preceding it.

I think we ought not to combine non-adjacent conditions after all. I'm working on a pull request to change that.
