### ISSUE TITLE
Initiate PRs for prereleases

### ISSUE THREAD

**Issue by jasongrout** [regro/cf-scripts#570]
Somewhat similar to the more complicated https://github.com/regro/cf-scripts/issues/105 (and perhaps related to https://github.com/regro/cf-scripts/issues/568), we would love to have automatic updates for prereleases from pypi. Basically, when the latest version on pypi is a prerelease, look for the existence of a `prerelease` branch. If it exists, make a PR updating the prerelease recipe.

I got as far as this in getting the latest prerelease from PyPI:

```python
diff --git a/conda_forge_tick/update_upstream_versions.py b/conda_forge_tick/update_upstream_versions.py
index 7018289..e286297 100644
--- a/conda_forge_tick/update_upstream_versions.py
+++ b/conda_forge_tick/update_upstream_versions.py
@@ -118,6 +118,21 @@ class PyPI:
             return False
         return r.json()["info"]["version"].strip()
 
+class PyPIPrerelease(PyPI):
+    name = "pypi-prerelease"
+
+    def get_version(self, url):
+        r = requests.get(url)
+        if not r.ok:
+            return False
+        versions = (v.strip() for v in r.json()["releases"].keys())
+        version = max(versions, key = lambda x: parse_version(x))
+
+        # Only return the latest release if it is a prerelease
+        if parse_version(version).is_prerelease:
+            return version
+        return False
+
```
But now it seems that the architecture might have to change a bit to accommodate multiple versions/PRs for a feedstock (one for stable, one for prerelease), as well as pruning the graph effectively based on the feedstock having a prerelease branch.

Thoughts? Do you suggest I just figure out how to use rever or something similar and build it into our release workflow?

**Comment by scopatz** [comment]
Hi @jasongrout! Generally conda-forge discourages the building of prereleases, due to CI bandwidth limitations. Having moved to Azure, a lot of those concerns have been alleviated (but we still can't afford to build every commit for every project). 

That said, if you are going to be building prereleases, they should get pushed to the `pre`, `prerelease`, or `rc` label, and NOT get pushed to the main label. This involves setting [the channel entry of conda-forge.yaml files](https://conda-forge.org/docs/maintainer/conda_forge_yml.html#channels) to be something like

```yaml
channels:
  # sources selects the channels to pull packages from, in order.
  sources:
    - conda-forge/label/pre
    - conda-forge
    - defaults
  # targets is a list of 2-lists, where the first element is the
  # channel to push to and the second element is the label on that channel
  targets:
    - ["conda-forge", "pre"]
```

For regular release, this would need to be removed / reset to the default value.

Having a prerelease branch on the main repo or pushing into master doesn't much matter, I don't think.

In many ways, it would be simpler to use rever in your release workflow. However, rever in its current form wouldn't handle the label switching, so the prereleases would still end up on the main label.
