### ISSUE TITLE
A path to handling ironically "strict" YAML

### ISSUE THREAD

**Issue by bollwyvl** [regro/cf-scripts#653]
Over on https://github.com/conda-forge/yamllint-feedstock/pull/18 I pulled out a feature of that feedstock where we used yamllint to lint its own recipe. To get there, we used this construction:
```yaml
package:
  name: '{% set name = "yamllint" %}{{ name }}'
  version: '{% set version = "1.15.0" %}{{ version }}'
```
... but the bot couldn't find the version bump, even when upstream packages were dropping, so we were merrily building that version over and over again.

I'd like to be able to add that typographic feature: while not _all_ conda recipes can be clean-as-the-driven-snow YAML, a lot _could_ be, and could benefit from the tooling being able to be linted. A longer con would be adding an opt-in `yamllint: true` to the bot, I suppose...

**Comment by bollwyvl** [comment]
(I have not xonsh'd in anger, and would appreciate a pointer to where to look in this repo to start)

**Comment by CJ-Wright** [comment]
I think you need to add your string template to the [regex for finding the version](https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/migrators.xsh#L341-L347) and

**Comment by CJ-Wright** [comment]
Most likely the thing that is tripping the bot up is the quotations. If you have a regex to fix that would you mind adding it to the checksum logic? That way we could address #184

**Comment by bollwyvl** [comment]
Great, thanks! I'll look into it!

**Comment by bollwyvl** [comment]
It's looking like I can't exactly have the syntax I used work for both conda-build and the bot, but my original goal of pure-YAML (is there such a thing) DRY recipes _can_ be made to work, with the broadly supported:
```yaml
package:
  name: |-
    {% set name = "yamllint" %}{{ name }}
  version: |-
    {% set version = "1.18.0" %}{{ version }}
```
As to the quoted shas (which are _probably_ a good idea)... still tinkering. Might need extra patterns...
